### PR TITLE
enable extensibility for custom Salesforce REST API calls creation

### PR DESCRIPTION
**Pull request by zacheusz**
Sometimes Salesforce exposes custom REST API calls - making the methods protected makes possible to create RestApi method implementations for custom Salesforce REST API calls. For example we are using the forked and changed api as a base for pulling SF reports via REST API calls. 

This is an updated version of the old pull request #18.

### CODE REVIEW

**Comment by jesperfj** [comment]
Thanks! Can you share a sample subclass?

**Comment by zacheusz** [comment]
this is the simplest example I think:

```java
import com.force.api.ApiConfig;
import com.force.api.ApiSession;

public class ForceApi extends com.force.api.ForceApi {

	public ForceApi(ApiConfig config, ApiSession session) {
		super(config, session);
	}

	public ForceApi(ApiConfig apiConfig) {
		super(apiConfig);
	}

	public ForceApi(ApiSession session) {
		super(session);
	}

	/**
	 * Returns a list of all approval processes. Can also be used to submit a
	 * particular record if that entity supports an approval process and one has
	 * already been defined. Records can be approved and rejected if the current
	 * user is an assigned approver. When multiple requests are passed to do bulk
	 * approvals, the requests that succeed are committed and the requests that
	 * don’t succeed send back an error.
	 * @see {@link https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_process_approvals.htm}
	 * 
	 * @param SF requests
	 * @return array of responses
	 */
	public ApprovalResponse[] approval(final ApprovalRequests requests) {
		return call("/process/approvals/", "POST", requests, 200, ApprovalResponse[].class);		
	}

}
```

**Comment by jesperfj** [comment]
I might not have thought this through, but couldn't that be achieved by making `call` a public method in `ForceApi` and implement your class as follows:

```
import com.force.api.ForceApi;

public class MyApprovals {
        ForceApi api;

	public MyApprovals(ForceApi api) {
		this.api=api;
	}

	/**
	 * Returns a list of all approval processes. Can also be used to submit a
	 * particular record if that entity supports an approval process and one has
	 * already been defined. Records can be approved and rejected if the current
	 * user is an assigned approver. When multiple requests are passed to do bulk
	 * approvals, the requests that succeed are committed and the requests that
	 * don’t succeed send back an error.
	 * @see {@link https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_process_approvals.htm}
	 * 
	 * @param SF requests
	 * @return array of responses
	 */
	public ApprovalResponse[] approval(final ApprovalRequests requests) {
		return api.call("/process/approvals/", "POST", requests, 200, ApprovalResponse[].class);		
	}

}
```

I haven't thought through if there are any generics issues here, but as you can tell, I would love to provide this extensibility through composition rather than subclassing.

**Comment by zacheusz** [comment]
I agree that composition sounds good, but I think that this is a rare case where inheritance would work better. Making the `call` method public exposes more inner working outside. Additionally, in some cases, you may need more than the `call` method - look at the methods I made protected. In the provided example the internal method `call` is still hidden outside the package and subclasses. I mean the API users can't reach it, but if you make it public then they will be able to mess with it.

**Comment by jesperfj** [comment]
I was actually curious what the motivation was for making the many other methods protected. I consider the "inner workings" exposed once a method is protected because a library user may then take a dependency on it and the library will have to be careful not to break compatibility. In that view, your proposed change creates a lot of exposure.

I kind of like the idea of a public method like your `call()` method. Perhaps it should be called something else, but it seems like a pretty meaningful thing to have since it adds support to some very valuable parts of Force.com API.

If you had this as a public method, do you know of anything else that would stand in your way?

**Comment by zacheusz** [comment]
I think that a public method would work fine as well.

**Comment by cswendrowski** [comment]
Just chiming in here - we had a need to communicate with the Salesforce Chatter API and used this project as a base for that work. The only core modifications that were needed was to override the following method where `community` was an additional object passed into the `ForceApi` constructor:

```
private final String uriBase() {
		return(session.getApiEndpoint()+"/services/data/"+config.getApiVersionString())+
                "/connect/communities/" + community.getId();
}
```

This allowed us to use the same CRUD methods that the API allows with new objects that represented the Chatter API.

I understand that this is a different use-case than your current discussion, but it is fairly related to the core issue of how extendable `ForceApi` should / shouldn't be. It is possible that using the suggested public `call` method may work for this case, but then we would lose out on reusing the existing `CRUD` methods.

**Comment by jesperfj** [comment]
Closing in favor of #41

**Pull request closed without merging**
