### PR TITLE
An overridden method to get more information from /describe API.

### PR DESCRIPTION
**Pull request by caltrain**
1. The newly written method enables anybody to inherit DescribeSObjectBasic and map jackson. 
2. Existing method functionality is unchanged. 
3. Tested the code using unit test testDescribeSObject().

Please let me know how I can improve this! Thank you

### CODE REVIEW

**Comment by jesperfj** [comment]
Can you share some examples for how you want to extend DescribeSObjectBasic? I am wondering if DescribeSObject should just be enhanced with those extensions right here in force-rest-api.

**Comment by caltrain** [comment]
Hi Jesper, 
Here is an example of how I extended DescribeSObjectBasic. 

```Java

import java.util.List;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import com.force.api.DescribeSObjectBasic;

/**
 * Derived from DescribeSObjectBasic. Serves as a medium to retrive more attributes that are not in the basic.
 * 
 * @author mvadivelu
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class DescribeSObjectAccount extends DescribeSObjectBasic {

    private List<RecordTypeEntity> recordTypeInfos;

    public List<RecordTypeEntity> getRecordTypeInfos() {
        return recordTypeInfos;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RecordTypeEntity {
        private boolean available;
        private boolean defaultRecordTypeMapping;
        private String name;
        private String recordTypeId;
        private String urls;

        public boolean isAvailable() {
            return available;
        }

        public String getName() {
            return name;
        }

        public String getRecordTypeId() {
            return recordTypeId;
        }
    }

    /**
     * Goes through the recordTypeInfos and tries to find the record of given name. Will return null if nothing found.
     * 
     * @param String, name of the record type
     * @return String RecordTypeId
     */
    public String getRecordTypeId(String name) {
        if (name != null) {
            for (RecordTypeEntity oneRecord : recordTypeInfos) {
                if (name.equalsIgnoreCase(oneRecord.getName())) {
                    return oneRecord.getRecordTypeId();
                }
            }
        }
        return null;
    }

}
```

**Comment by jesperfj** [comment]
I have gotten a little rusty recently on SFDC API, but I believe DescribeSObjectResult is a pretty static schema that doesn't evolve much. I think I was just lazy when I first implemented this class and didn't build complete support for the schema.

So I am thinking whether we should attempt to just support the whole schema in the library class? Or is that too ambitious?

**Comment by caltrain** [comment]
It would take long time to identify all the common attributes and support it. 
I didn't want to break the existing library by introducing a new attribute that does not exist if anyone attempts to do a /describe on a custom SObject. 

Hence I went in this direction: Provide a way to for querying. What attributes they want is upto them :)

**Pull request closed without merging**
