### PR TITLE
enable extensibility for custom Salesforce REST API calls

### PR DESCRIPTION
**Pull request by zacheusz**
sometimes Salesforce exposes custom REST API calls - making the methods protected makes possible to create RestApi method implementations for custom Salesforce REST API calls

### CODE REVIEW

**Comment by jesperfj** [comment]
I'd love to merge this in, but I haven't touched this repo in a long time and tests are failing now. I'd like to get the existing tests passing again before merging. Any help would be much appreciated.

**Comment by zacheusz** [comment]
As you can clearly see the change doesn't affect any existing functionality and does not correspond with the existing tests. Curently I have no time to check your tests (maybe in the future). The code I'm providing is well tested - I'll add JUnit tests in the future (need to separate them from different project).

**Comment by zacheusz** [comment]
@jesperfj I saw that you merged some pull requests - are the tests working now?

**Comment by jesperfj** [comment]
I haven't looked at this PR in a while. The library has evolved just enough that this branch has conflicts but they look pretty trivial. If you can merge master into this branch and resolve conflicts, I'll take a look at it.

**Comment by jesperfj** [comment]
I am going to close this. Plz do a new PR if you want to still pursue this.

**Comment by zacheusz** [comment]
@jesperfj I created a new PR #37 which is ready to automatic merge. We are using this piece of code for about two years.

**Pull request closed without merging**
