### PR TITLE
Adds way to calculate out Version string using the Season and Year

### PR DESCRIPTION
**Pull request by cswendrowski**

### CODE REVIEW

**Comment by jesperfj** [comment]
Neat.

I would suggest renaming `ApiVersionSeason` to just `Season`. I think it's pretty unambiguous and more DRY.

I would suggest renaming `setApiVersionString` to `setSeason`. I know it'll be a bit more clear to do something like `setApiVersionSeason` or `setApiVersionFromSeason`, but I think `setSeason` is again fairly unambiguous.

What do you think?

**Comment by cswendrowski** [comment]
@jesperfj you are extremely fast to reply!

`Season` seems like an appropriate name for that class, I will make that change.

When naming the ApiConfig method, I landed on `setApiVersionString(Season, year)` since it makes it very clear that it does the same thing as `setApiVersionString(String)` but with different inputs and that the resulting value can be returned via `getApiVersionString()`

`setSeason` doesn't seem to carry the intent as well, and implies there is a `Season` variable stored on the Object. `setApiVersionFromSeason` carries intent, but is a bit lengthy and would be more correct as `setApiVersionStringFromSeasonAndYear` which is a mouthful.

**Comment by jesperfj** [comment]
Hm good points. Now I regret calling it `setVersionString` way back :-). Since now there are 3 ways of setting version taking 3 different sets of arguments, maybe they should all be called `setVersion`?

**Comment by cswendrowski** [comment]
@jesperfj `setVersion` with 3 different arguments seems like the best way forward. `getVersionString` could be removed and `getVersion` could then be un-deprecated and just return a `String`

**Comment by cswendrowski** [comment]
Closing in favor of #40

**Pull request closed without merging**
