### PR TITLE
Adding support for "If-Modified-Since" http header to only return met…

### PR DESCRIPTION
**Pull request by vkolotov**
Hi @jesperfj, thank you for your great effort to maintain your library.

Could you please have a look what I've done to add support for the "If-Modified-Since" http header in the describe method?

Here are some details:
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/sobject_describe_with_ifmodified_header.htm

Thanks,
Vlad

### CODE REVIEW

**Comment by jesperfj** [comment]
Can you share some code snippets showing how you will be using this? Are you caching previous DescribeObject instances?

**Comment by vkolotov** [comment]
Hi @jesperfj this feature mainly is used when you want to optimise interaction between your client and Salesforce, for example for mobile apps. Our app sends periodic request to describe object to get picklist values, and if, and only if, there were some changes since the last time (last request), the picklist values get returned and processed.

**Comment by jesperfj** [comment]
Hi @vkolotov 

I am curious how you store the cached values. For example, if you cache an instance of DescribeSObject, I'd like to consider passing back the same instance to ForceApi, something like this:

```
myDescribeSObject = api.refreshDescribeSObject(myDescribeSobject);
```
(method name tbd).

Then ForceApi would be responsible for time stamping DescribeSObjects when retrieving them and using that timestamp to do a conditional get.

**Comment by jesperfj** [comment]
On second thoughts, I am guessing it is common to want to check if an update occurred. My proposal makes that unnecessarily complicated.

**Comment by vkolotov** [comment]
Hi @jesperfj,

As as mentioned earlier we use this feature to minimise payload footprint between our mobile app and its API (server part). This is what happens:

1. Initially the mobile app sends a request where it specifies "since" date == null. This means it needs to get ALL data. For example, it needs to have ALL picklist values for an object in Salesforce.
2. The server (API) responds with ALL picklist values but also sends a date that specifies when was this interaction happened.
3. Later on, the app checks if there are any changes since the last time it talked to the server by providing the date specified on #2. 
4. The server uses this date in SOQL and in the describe REST api call to "ask" Salesforce if it has any changes since the last time. If it has changes, then only what has changed is returned to he mobile app. If there is not any change, then nothing is returned to the mobile app apart from a new date (that is going to be used next time).

Hopefully I described this more clear now. Looking forward to seeing this new feature in the upstream.

Thanks,
Vlad

**Pull request merged**
