### PR TITLE
If modified since for describeSObject

### PR DESCRIPTION
**Pull request by jesperfj**
This is a tweaked proposal for #59. @vkolotov if you like this proposal, we can move the PR discussion here.

### CODE REVIEW

**Comment by vkolotov** [comment]
Hi @jesperfj thanks for that. I'll check it today on a real world example and let you know.

**Comment by vkolotov** [comment]
Hi @jesperfj, it is working for me well. Thanks!

**Comment by jesperfj** [comment]
@vkolotov I am having a weird problem where my DescribeTest fails when I run the tests locally, but when I run them on Heroku CI, they pass successfully. There is also a bug in my tests and they're not really all that good to begin with.

Since you have some working code, can you help by writing a better test?

**Comment by vkolotov** [comment]
Hi @jesperfj, I'm happy to help you with unittesting. I tried to set up SF sandbox as it stated in your doc: https://github.com/jesperfj/force-rest-api#run-tests 

I'm stuck at "Now create a new Remote Access Application:". Looks like SF has updated some config screens so I no longer can do what's said in your doc.

Could you please help me with that? Or even better update that small section on how to set up testing sandbox?

**Comment by jesperfj** [comment]
I updated instructions

**Pull request merged**
