### PR TITLE
Generic get, post, put, patch and delete REST methods

### PR DESCRIPTION
**Pull request by jesperfj**
This code adds new public methods to address the needs in #37 without resorting to subclassing.

@zacheusz and @cswendrowski, let me know what you think. I am shooting for having explicit methods for get, post, put, delete and patch instead of taking these verbs as parameters.

For now, it is only supporting JSON request contents andis  always expecting a JSON body in the response. This can be made more flexible at a later point.

### CODE REVIEW

**Comment by zacheusz** [comment]
Sounds like a good idea to limit and hide the method selection. However, you have some duplicated code here. What about creating one private `call` method with exception and expected return code handling and then wrapping it into `post` `get` etc. methods?

**Comment by jesperfj** [comment]
Yes. I am going to clean that up. I can probably also dedup the SObject
CRUD methods. I just wanted to get a sense of if this approach would
address your use cases.

**Comment by zacheusz** [comment]
Yes it looks like it will be fine. Thanks a lot!

**Comment by jesperfj** [comment]
I am ambivalent about having an extra `get` method that splits out the query string (as is in there right now). Perhaps it's overkill? I am not even preventing users from putting query string in the path argument in the one-arg version. So I think I am going to delete the extra 2-argument `get` method.

**Comment by jesperfj** [comment]
This is ready to be merged. Would be great if you can take a look @zacheusz.

It's possible people will run into constraints using this. But it's easier to decide to relax those constraints once there are specific cases to look at, e.g. response codes not matching up.

**Comment by jesperfj** [comment]
Oh, and there is some future clean-up to do. With the new methods introduced here, a lot of the existing methods can be rewritten and de-duped. I just want this to sit for a little bit and prove itself before touching old, proven code.

**Comment by jesperfj** [comment]
Reviews still welcome, but this is now merged and released in 0.0.35.

**Comment by jesperfj** [comment]
I think it definitely needs to offer a nice way to check for NOT_FOUND / 404 on an attempted delete since it's probably a common pattern to try to delete something that doesn't exist and then checking for success/failure.

There is even an open pull request related to that: #26

**Comment by jesperfj** [comment]
Hm ok. I'll need to make it more flexible then. Chatter posts return 201.

**Pull request merged**
