### PR TITLE
Updated Jackson libraries from 1.0 to 2.0.

### PR DESCRIPTION
**Pull request by emckissick**
-Includes import changes
-Includes update of traversing root nodes to the Jackson 2.0 builder format.

### CODE REVIEW

**Comment by emckissick** [comment]
Not sure if this could be another version of the Force-Rest-Api, but just thought I'd take a stab at updating it to Jackson 2.0.

**Comment by jesperfj** [comment]
I'd love to merge this in, but I haven't touched this repo in a long time and tests are failing now. I'd like to get the existing tests passing again before merging. Any help would be much appreciated.

**Comment by emckissick** [comment]
Will do, I'll try to look at them sometime this weekend.

**Comment by emckissick** [comment]
So a lot of the SOAP login tests are failing because of the need for a Security Token to be appended to the password https://www.salesforce.com/developer/docs/api/Content/sforce_api_concepts_security.htm#topic-title_login_token

OAuth requests still work as expected

It looks like API calls require the token by default after v31
Require security tokens for API logins from callouts (API version 31.0 and earlier)

I'm not sure if this warrants adding a new parameter to the ApiConfig securityToken.

I'll make another pull request with this change for consideration.

**Comment by emckissick** [comment]
Created the following pull request from the master branch
https://github.com/jesperfj/force-rest-api/pull/22

After changing this, the tests that use the SOAP login pass.

**Comment by jesperfj** [comment]
Hm. I normally just append the security token to the password. I am not convinced it should be a separate parameter since it's standard practice across all SFDC APIs and tools to append it to the password.

I found other bugs in the code too (bit rot basically). I think I fixed them all and tests should now pass on master if you append security token to password in the test properties. Can you verify?

**Comment by emckissick** [comment]
Yep, verified.  I appended the token to the password and now the tests pass. I'll close out the other pull request.

**Comment by jesperfj** [comment]
I checked too and tests pass for your code. Now the question is how confident we should be in those tests :-). How big a change do you think it is to switch to jackson 2? I won't have the time to really dig into it'll have to be a judgment call. What does traverse() do? What other major things changed?

**Comment by emckissick** [comment]
Traverse() returns a JsonParser for a JsonNode.  In the older Jackson the ObjectMappers readValue could take a JsonNode, but in 2.0 it needs a JsonParser.

**Comment by emckissick** [comment]
Per the Jackson 2.0 side

>API changes, misc.

>This section lists other API-level changes from Jackson 1.x, in no particular order; both completed (if not mentioned) and potential (where explicitly noted)

>ObjectMapper
registerModule: changed to return 'this' (ObjectMapper it is called on) -- this is binary-incompatible change so must be done with major version upgrade
Other similar changes will be done where applicable, from 'void' to "this".
JsonSerializable

>JsonSerializer now includes method 'serializeWithType()', which used to be in separate interface JsonSerializableWithType: by default, i

>SerializationConfig.Feature, DeserializationConfig.Feature
Two main enumerations used for configuring serialization and deserialization settings have been refactored AND renamed, so that:

>Features that were shared between the two, and which can NOT be changed on per-call basis, are now defined as MapperFeature: this includes fundamental annotation introspection settings
Other features are included in two new Enums, with more convenient names:
DeserializationFeature (for former DeserializationConfig.Feature)
SerializationFeature (for former SerializationConfig.Feature)
Usage is otherwise similar, with respect to ObjectMapper, but it is now possible to reconfigure ObjectMapper and ObjectWriter as well, using:


   `ObjectWriter w = mapper.writer().with(SerializationFeature.INDENT_OUTPUT);
   ObjectReader r = mapper.reader().without(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);`

>More Immutability
One of half-done good ideas with 1.x is to try to make certain objects fully immutable, in somewhat functional style. This is a useful goal mostly for making multi-threaded operation simpler, safer and potentially slightly faster.

>Completed changes:
JavaType
DeserializationConfig
SerializationConfig
Some objects that we probably won't/can't make fully immutable:

>ObjectMapper: it seems impractical to try this, given both that we already have immutable "replacements" (ObjectReader, ObjectWriter), and because typically there has to be some small piece that is mutable to keep things easy to use (and often hide impl details of how immutable aspects work)
JsonFactory: we could probably get immutability working if ObjectMapper was the only user; but it may be difficult to get this to work for "direct" usage (i.e. Streaming Api use case)
Misc other API changes

>Classes moved:
"TokenBuffer" is only used by mapper and was moved to 'jackson-databind' package from core: the main benefit is that this is 20kB less stuff in streaming-api package, and reduces/removes need for separate "mini" jar.
Classes removed:
CustomSerializerFactory, CustomDeserializerFactory removed: all functionality should be available through Module interface
Annotations moved:
JacksonInject, JsonFilter, JsonRootName JsonView moved to core annotations (since it has no dependencies to mapper package).
Functional changes

>"Any setter" vs ignored properties
In 1.x, any properties defines as ignored using @JsonIgnore will also be blocked from being set using so-called "any setters". This only affects properties not passed via regular deserialization accessors (fields, setters, constructor parameters).
In 2.0, this will not be done; only properties defined using @JsonIgnoredProperties are excluded, but @JsonIgnore will not have any effect on things passed to any-setters.

**Comment by emckissick** [comment]
As for how big the change was...It was mostly package changes and using JsonParser instead of nodes and using .set instead of put on the ObjectNode.  

>JsonNode	put(String fieldName, JsonNode value)
Deprecated. 
Since 2.4 use either set(String,JsonNode) or replace(String,JsonNode),

The difference I see from Jackson 1 vs. Jackson 2 is that 
The last Jackson 1 release was Jackson 1.9.13  on 14-Jul-2013
The last Jackson 2 release was Jackson 2.5.0 on 01-Jan-2015

I submitted this pull request because I had to include both the Jackson jars in my application.  One for the existing Jackson 2.0 mappers and annotations and another for the Force Rest Api mappings using Jackson 1.9.  

Those who are using Jackson 1.9 and grab a newer version of the Force-Rest-Api (if my PR makes it) will experience the same issue I had or be forced to upgrade there application or stay at the previous version.  So I guess thats one of the negatives from a user perspective.

**Comment by emckissick** [comment]
As for the confidence in the tests....I believe some of the ones in the ForceApi class could be Unit tested and not just Integration tested, like normalizeCompositeResults.  I do have a question about the testDiscoverSObject.  It tries to get the recentItems that for Contacts...looks like this
{"attributes":{"type":"Contact","url":"/services/data/v33.0/sobjects/Contact/0031a000002UFGeAAO"},"Id":"0031a000002UFGeAAO","Name":"LastName, FirstName"}

I'll add the name to the Contact class, so I can check the RecentItems Contact creation.

**Comment by jesperfj** [comment]
I merged it all in. I did it locally, so not sure if I should just close this PR or merge it.

**Comment by emckissick** [comment]
Whichever works best for your deployment process is ok with me.

**Comment by jesperfj** [comment]
Closing. Merged separately: ec5fc13f4da96cfc208e9e27ee1d9869967d1708

**Pull request closed without merging**
